Messages:
  NoPermissions: "&cYou do not have the required permissions!"
  ConfigReloaded: "&aSuccessfully reloaded config!"
  InvalidArgs: "&cInvalid arguments! Correct usage: /chatactions <reload:spy>"
  SpyEnabled: "&aSpy mode enabled!"
  SpyDisabled: "&cSpy mode disabled!"
  SpyFormat: "[%action%] %player%: %msg%"
  Cooldown: "&cPlease wait %time% more seconds before talking in %channel%!"

Channels:
  Global:
    format: "%player% &6>> &6%msg%"
    range: 0
    permission: "chatactions.channels.global"
    prefix: "!"
    suffix: ""
    cooldown: 2
  Normal:
    format: "%player% &6>>&2 %msg%"
    range: 10
    permission: "chatactions.channels.normal"
    cooldown: 0
  Whisper:
    format: "%player% &6>>&r %msg%"
    prefix: "*"
    suffix: ""
    range: 3
    permission: "chatactions.channels.whisper"
    cooldown: 5
  Action:
    format: "%player% &8 %msg%"
    prefix: "+"
    suffix: ""
    range: 15
    permission: "chatactions.channels.whisper"
    cooldown: 5
  TheFate:
    format: "&3%msg%"
    prefix: "#"
    suffix: ""
    range: 20
    permission: "chatactions.channels.thefate"
    cooldown: 5
  Environment:
    format: "&9%msg%"
    prefix: "%"
    suffix: ""
    range: 20
    permission: "chatactions.channels.environment"
    cooldown: 5
  Yell:
    format: "%player% &6>>&c %msg%"
    prefix: ""
    suffix: "!"
    range: 20
    permission: "chatactions.channels.whisper"
    cooldown: 5
  Scream:
    format: "%player% &6>>&4 %msg%"
    prefix: ""
    suffix: "!!"
    range: 30
    permission: "chatactions.channels.whisper"
    cooldown: 5

#SaveTheGame Settings
#Should the players display name or account name be displayed?
#true - display name
#false - account name
displayname: true

#Show the time beside each line?
displayTime: false

#Max amount of logs a player can have
#Keep it less than 9
amountOfLogs: 4